/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createBusServiceFromDiscriminatorValue, type BusService } from '../../../models/';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /BusStops/{Code}/Services
 */
export interface ServicesRequestBuilder extends BaseRequestBuilder<ServicesRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<BusService[]>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<BusService[] | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const ServicesRequestBuilderUriTemplate = "{+baseurl}/BusStops/{Code}/Services";
/**
 * Metadata for all the requests in the request builder.
 */
export const ServicesRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: ServicesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createBusServiceFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
