/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createTrainStationCrowdFromDiscriminatorValue, type TrainStationCrowd } from '../models/';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /Stations
 */
export interface StationsRequestBuilder extends BaseRequestBuilder<StationsRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<TrainStationCrowd[]>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<TrainStationCrowd[] | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const StationsRequestBuilderUriTemplate = "{+baseurl}/Stations";
/**
 * Metadata for all the requests in the request builder.
 */
export const StationsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: StationsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createTrainStationCrowdFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
