/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type AdditionalDataHolder, type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

export interface BusStop extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The code property
     */
    code?: string;
    /**
     * The description property
     */
    description?: string;
    /**
     * The latitude property
     */
    latitude?: number;
    /**
     * The longitude property
     */
    longitude?: number;
    /**
     * The roadName property
     */
    roadName?: string;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {BusStop}
 */
export function createBusStopFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoBusStop;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
export function deserializeIntoBusStop(busStop: Partial<BusStop> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "code": n => { busStop.code = n.getStringValue(); },
        "description": n => { busStop.description = n.getStringValue(); },
        "latitude": n => { busStop.latitude = n.getNumberValue(); },
        "longitude": n => { busStop.longitude = n.getNumberValue(); },
        "roadName": n => { busStop.roadName = n.getStringValue(); },
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
export function serializeBusStop(writer: SerializationWriter, busStop: Partial<BusStop> | undefined = {}) : void {
    writer.writeStringValue("code", busStop.code);
    writer.writeStringValue("description", busStop.description);
    writer.writeNumberValue("latitude", busStop.latitude);
    writer.writeNumberValue("longitude", busStop.longitude);
    writer.writeStringValue("roadName", busStop.roadName);
    writer.writeAdditionalData(busStop.additionalData);
}
/* tslint:enable */
/* eslint-enable */
