/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createBusStopFromDiscriminatorValue, type BusStop } from '../models/';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /bus-stops
 */
export interface BusStopsRequestBuilder extends BaseRequestBuilder<BusStopsRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<BusStop[]>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<BusStop[] | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const BusStopsRequestBuilderUriTemplate = "{+baseurl}/bus-stops";
/**
 * Metadata for all the requests in the request builder.
 */
export const BusStopsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: BusStopsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createBusStopFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
